### ISSUE TITLE
multiple log level

### ISSUE THREAD

**Issue by narimanam** [jukkahell/nestlogger#16]
Hi,
is there a way to add multiple log levels to a single logger? something like this:
` const logger = new LoggerService(
                            'info error warning',
                            loggers,
                        );`

**Comment by jukkahell** [comment]
If you set your level to info then it will log warnings and errors as well. Or is there something more specific that you need to achieve?

**Comment by jukkahell** [comment]
It seems that winston supports custom log levels too: https://github.com/winstonjs/winston/blob/master/examples/custom-levels.js  I can implement that if that is what you would like to have?

**Comment by narimanam** [comment]
yes, that'll be nice

**Comment by jukkahell** [comment]
This is done and published in 6.1.0
