### ISSUE TITLE
Options not passed to transport constructors

### ISSUE THREAD

**Issue by prg** [jukkahell/nestlogger#7]
I just tried to extend your module with a `level` option for transports, which winston apparently supports.

Quickly found out that neither `console` nor `rotate` actually pass the supplied options to winston's transport constructors.

In case of `console` it's just empty:
```typescript
public static console(options?: LoggerOptions): ConfiguredTransport {
...
    const transport = new winston.transports.Console();
...
}
```

In case of `rotate` some explicitly specified options are passed, the rest is discarded?
```typescript
  public static rotate(options?: LoggerOptions): ConfiguredTransport {
    const defaultOptions = Object.assign({}, LoggerService.DEFAULT_LOGGER_OPTIONS);
    const fileLoggerOptions = Object.assign(defaultOptions, options);
    const transport = new DailyRotateFile({
...
      maxFiles: fileLoggerOptions.maxFiles,
      options: { flags: "a", mode: "0776" },
    });
    return { transport, options: fileLoggerOptions };
  }
```

Is there something I'm missing? For example, shouldn't `console` look something like the following?
```typescript
  public static console(options?: LoggerOptions): ConfiguredTransport {
    const defaultOptions = Object.assign({}, LoggerService.DEFAULT_LOGGER_OPTIONS);
    const consoleLoggerOptions = Object.assign(defaultOptions, options);
    const transport = new winston.transports.Console(consoleLoggerOptions);
    return { transport, options: consoleLoggerOptions };
  }
```

**Comment by jukkahell** [comment]
You have a good point. It currently assigns only options that I've chosen to support. Doesn't feel that nice to add every supported option separately.

I can try to find a solution for that this week! I'm also really happy for any suggestions and PRs 👍

**Comment by jukkahell** [comment]
Actually did a quick rewrite already for this into this branch: https://github.com/jukkahell/nestlogger/tree/feature/support-all-transport-options

Updated the README with the new way to pass in the options. But in short,
LoggerOptions now has consoleOptions and fileOptions as a separate properties which are the actual Winston's transport options. To override the level you'd do it like this:
```javascript
   const loggers = [
      LoggerService.console({
        timeFormat: "HH:mm",
        consoleOptions: {
          level: "info",
        },
      }),
      LoggerService.rotate({
        colorize: false,
        fileOptions: {
          filename: `${config.logger.path}/${config.serviceName}-%DATE%.log`,
            level: "error",
        },
      }),
   ];
```
What do you say?

**Comment by prg** [comment]
Just quickly glanced over it, looking good to me so far.

As far as I can tell, this would support any additional option on the `console`/`DailyRotateFile` transports? Like for instance the `createSymlink` option on the `DailyRotateFile` transport?

**Comment by jukkahell** [comment]
Exactly. I'll merge my PR and close this issue. Feel free to report new issues if there is anything.
